### ISSUE TITLE
PluginInstaller.php Issue

### ISSUE THREAD

**Issue by Thomanji** [roundcube/plugin-installer#23] opened 2019-12-07 04:10 UTC
Hi,

I am facing a issue and wondered if I could get a pointer if I do something wrong or if there is a issue. I just upgraded to Rouncube 1.4.1 and everything worked great.
However, I am trying to install some plugins with composer and get a error when I run

php composer.phar update

Fatal error: Cannot pass parameter 2 by reference in roundcube/vendor/roundcube/plugin-installer/src/Roundcube/Composer/PluginInstaller.php on line 272

So on line 272 is:

$exitCode = $process->execute($script, null, $plugin_dir);

I checked and in the latest version of PluginInstaller.php the second parameter is still "null".

Any tip of info would be very much appreciated.

**Comment by alecpl** [comment] 2019-12-07 07:56
I transferred the ticket to proper repository.

What PHP version? What plugins do you have in your composer file? While the code bug is obvious, I think that code path is hit only by not so many plugins.

**Comment by Thomanji** [comment] 2019-12-11 02:00
Hi, Thank you for responding and sorry for not posting it correctly.

In my case PHP is 5.6.40

Below is my composer file content

{
    "name": "roundcube/roundcubemail",
    "description": "The Roundcube Webmail suite",
    "license": "GPL-3.0+",
    "repositories": [
        {
            "type": "composer",
            "url": "https://plugins.roundcube.net/"
        },
        {
            "type": "pear",
            "url": "https://pear.php.net/"
        },
        {
            "type": "vcs",
            "url": "https://git.kolab.org/diffusion/PNL/php-net_ldap.git"
        },
        {
            "type": "composer",
            "url": "https://plugins.roundcube.net"
        }
    ],
    "require": {
        "php": ">=5.6.0",
        "roundcube/rcsample": ">=0.2.0",
        "roundcube/plugin-installer": "~0.1.6",
        "pear/mail_mime": "~1.10.0",
        "pear/net_smtp": "~1.8.1",
        "patchwork/utf8": "1.2.x",
        "mat_krauser/image_paster": "1.0.x",
        "melanie2/owncloud": ">=0.2",
        "pear/pear-core-minimal": "~1.10.10",
        "pear/net_socket": "~1.2.1",
        "pear/auth_sasl": "~1.1.0",
        "pear/net_idna2": "~0.2.0",
        "pear/crypt_gpg": "~1.6.3",
        "pear/net_sieve": "~1.4.3",
        "endroid/qr-code": "~1.6.5",
        "masterminds/html5": "~2.5.0"
    },
    "minimum-stability": "dev"
}

Thank you for your assistance on this. Any further info you need, I am happy to supply or test possible solutions.

**Comment by alecpl** [comment] 2019-12-11 19:31
What plugins did you try to install? These in your composer does not contain any script - cannot reproduce.

**Closed** 2020-11-01 18:59 UTC
